# Generated by Django 4.1.7 on 2023-03-18 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('competence', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication', models.BooleanField(default=False)),
                ('date_limite', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
