# Generated by Django 4.1.7 on 2023-03-18 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
