# Generated by Django 4.1.7 on 2023-04-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0005_alter_offre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='image',
        ),
    ]
