# Generated by Django 4.1.7 on 2023-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0006_remove_offre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='image',
            field=models.ImageField(default='icon_about.png', upload_to='uploaded_images/'),
        ),
    ]
