# Generated by Django 4.2.1 on 2023-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0008_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='lancer',
            field=models.BooleanField(default=False),
        ),
    ]
