# Generated by Django 4.2.1 on 2023-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0009_demande_lancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='date_limite',
            new_name='duree',
        ),
    ]
