# Generated by Django 4.2.1 on 2023-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0010_rename_date_limite_demande_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='duree',
            field=models.CharField(max_length=100),
        ),
    ]
