# Generated by Django 4.2.1 on 2023-06-08 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0011_alter_demande_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='rapport',
            field=models.TextField(default='En cours'),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(default='En cours', max_length=100),
        ),
    ]
