# Generated by Django 4.2.1 on 2023-06-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0012_demande_date_debut_demande_date_fin_demande_rapport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Etat',
            field=models.CharField(default='Traitement', max_length=50),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(default='nouveau projet', max_length=100),
        ),
    ]
