# Generated by Django 4.2.1 on 2023-06-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0016_demande_cahier_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='date_debut',
            new_name='date_limite',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='date_fin',
            new_name='date_publication',
        ),
    ]
