# Generated by Django 4.2.1 on 2023-06-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0017_rename_date_debut_demande_date_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.BooleanField(default=False)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recructement.demande')),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recructement.architect')),
            ],
        ),
    ]
