# Generated by Django 4.2.1 on 2023-06-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recructement', '0018_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='architect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
