# Generated by Django 4.2.1 on 2023-06-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0019_alter_decision_architect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='decision',
            new_name='decisionA',
        ),
    ]
