# Generated by Django 4.2.1 on 2023-06-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0020_rename_decision_decision_decisiona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='appel',
        ),
    ]
