# Generated by Django 4.2.1 on 2023-06-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0021_remove_decision_appel'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='demade',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='recructement.demande'),
        ),
    ]
