# Generated by Django 4.2.1 on 2023-06-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0022_decision_demade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decisionA',
            field=models.IntegerField(),
        ),
    ]
