# Generated by Django 4.2.1 on 2023-06-14 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0023_alter_decision_decisiona'),
    ]

    operations = [
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architect', models.CharField(max_length=200)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(default='nouveau projet', max_length=100)),
                ('rapport', models.TextField(default='En cours', null=True)),
                ('demande', models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='recructement.demande')),
            ],
        ),
    ]
