# Generated by Django 4.2.1 on 2023-06-14 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0024_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='architect',
        ),
        migrations.AlterField(
            model_name='projet',
            name='demande',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='recructement.decision'),
        ),
    ]
