# Generated by Django 4.2.1 on 2023-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0026_alter_projet_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='architecte',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
