# Generated by Django 4.2.1 on 2023-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0028_alter_realisation_architect'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='decisioncli',
            field=models.IntegerField(null=True),
        ),
    ]
