# Generated by Django 4.2.1 on 2023-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0029_decision_decisioncli'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='verification',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
