# Generated by Django 4.2.1 on 2023-06-30 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recructement', '0030_architect_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Étape', models.CharField(max_length=500)),
                ('sous_etape', models.CharField(max_length=500, null=True)),
                ('Date_debut', models.DateField(default=django.utils.timezone.now)),
                ('Date_fin', models.DateField(default=django.utils.timezone.now)),
                ('Rapport', models.FileField(null=True, upload_to='cvs')),
                ('projet', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='recructement.projet')),
            ],
        ),
    ]
